apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  annotations:
        "opflex.cisco.com/endpoint-group": '{"policy-space":"kube","name":"epg-a"}'
spec:
  containers:
  - name: pod-a
    image: alpine
    command: ["sleep"]
    args: ["7200"]
