apiVersion: v1
kind: Pod
metadata:
  name: pod-b6020
  annotations:
        "opflex.cisco.com/endpoint-group": '{"policy-space":"kube","name":"epg-b"}'
spec:
  containers:
  - name: pod-b6020
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "nc -l -p 6020"]
